# Generated by Django 2.1.4 on 2019-01-10 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creatorprofile_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commentor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('creator_post', models.ManyToManyField(to='core.CreatorPost')),
            ],
        ),
    ]
