# Generated by Django 2.1.4 on 2019-01-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creatorpostcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorpostcomment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='creatorpostcomment',
            name='creator_post',
        ),
        migrations.DeleteModel(
            name='CreatorPostComment',
        ),
    ]
