# Generated by Django 2.1.4 on 2019-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190110_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorpost',
            name='video',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
