# Generated by Django 2.1.4 on 2019-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creatorpost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
