# Generated by Django 2.1.5 on 2019-01-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190117_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='img_folder/'),
        ),
    ]
